# Generated for IEA Team Portal v1.0.1
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True
    dependencies=[("auth","0012_alter_user_first_name_max_length")]
    operations=[
      migrations.CreateModel(name="Team",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=150)),("short_name",models.CharField(blank=True,max_length=60)),("discipline",models.CharField(choices=[("hunt_seat","Hunt Seat"),("western","Western"),("dressage","Dressage"),("multi","Multi-discipline")],default="hunt_seat",max_length=30)),("website",models.URLField(blank=True)),("logo",models.ImageField(blank=True,help_text="Use only a logo your team is authorized to display.",null=True,upload_to="team_logos/"))]),
      migrations.CreateModel(name="Season",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(help_text="Example: 2026–2027",max_length=50)),("start_date",models.DateField()),("end_date",models.DateField()),("is_active",models.BooleanField(default=False)),("team",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="seasons",to="portal.team"))],options={"ordering":["-start_date"]}),
      migrations.CreateModel(name="Rider",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("first_name",models.CharField(max_length=80)),("last_name",models.CharField(max_length=80)),("preferred_name",models.CharField(blank=True,max_length=80)),("school",models.CharField(blank=True,max_length=150)),("grade",models.PositiveSmallIntegerField(blank=True,null=True)),("iea_member_number",models.CharField(blank=True,max_length=40)),("bio",models.TextField(blank=True)),("photo",models.ImageField(blank=True,null=True,upload_to="riders/")),("active",models.BooleanField(default=True)),("guardians",models.ManyToManyField(blank=True,related_name="guardian_riders",to="auth.user")),("team",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="riders",to="portal.team")),("user",models.OneToOneField(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="rider_record",to="auth.user"))],options={"ordering":["last_name","first_name"]}),
      migrations.CreateModel(name="UserProfile",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("role",models.CharField(choices=[("admin","Administrator"),("coach","Coach"),("parent","Parent/Guardian"),("rider","Rider")],default="parent",max_length=20)),("phone",models.CharField(blank=True,max_length=30)),("team",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="user_profiles",to="portal.team")),("user",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="profile",to="auth.user"))]),
      migrations.CreateModel(name="SeasonMembership",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("division",models.CharField(blank=True,max_length=100)),("class_level",models.CharField(blank=True,max_length=100)),("notes",models.TextField(blank=True)),("rider",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="memberships",to="portal.rider")),("season",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="memberships",to="portal.season"))]),
      migrations.CreateModel(name="Announcement",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("title",models.CharField(max_length=160)),("body",models.TextField()),("priority",models.CharField(choices=[("normal","Normal"),("important","Important"),("urgent","Urgent")],default="normal",max_length=20)),("published",models.BooleanField(default=True)),("created_at",models.DateTimeField(auto_now_add=True)),("expires_at",models.DateTimeField(blank=True,null=True)),("created_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="auth.user")),("season",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="announcements",to="portal.season")),("team",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="announcements",to="portal.team"))],options={"ordering":["-created_at"]}),
      migrations.CreateModel(name="CalendarEvent",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("title",models.CharField(max_length=160)),("kind",models.CharField(choices=[("show","Show"),("lesson","Lesson"),("meeting","Meeting"),("deadline","Deadline"),("social","Social"),("other","Other")],default="other",max_length=20)),("starts_at",models.DateTimeField()),("ends_at",models.DateTimeField(blank=True,null=True)),("location",models.CharField(blank=True,max_length=200)),("description",models.TextField(blank=True)),("visible_to_all",models.BooleanField(default=True)),("season",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="events",to="portal.season")),("team",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="events",to="portal.team"))],options={"ordering":["starts_at"]}),
      migrations.AddConstraint(model_name="seasonmembership",constraint=models.UniqueConstraint(fields=("rider","season"),name="unique_rider_season")),
    ]
