from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("portal", "0001_initial")]

    # This migration shipped before the v1.2 schema-reconciliation work. Some
    # installations can therefore have all or part of these tables physically
    # present while django_migrations does not record 0002. Reconcile the
    # PostgreSQL schema idempotently and separately record normal Django state.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=r"""
                    -- Show -------------------------------------------------------
                    CREATE TABLE IF NOT EXISTS portal_show (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(180) NOT NULL,
                        show_date date NOT NULL,
                        start_time time NULL,
                        venue varchar(180) NOT NULL DEFAULT '',
                        address varchar(255) NOT NULL DEFAULT '',
                        host_team varchar(180) NOT NULL DEFAULT '',
                        iea_zone varchar(40) NOT NULL DEFAULT '',
                        iea_region varchar(40) NOT NULL DEFAULT '',
                        status varchar(20) NOT NULL DEFAULT 'planning',
                        entry_deadline date NULL,
                        notes text NOT NULL DEFAULT '',
                        season_id bigint NOT NULL,
                        team_id bigint NOT NULL
                    );
                    ALTER TABLE portal_show ADD COLUMN IF NOT EXISTS name varchar(180) NOT NULL DEFAULT '';
                    ALTER TABLE portal_show ADD COLUMN IF NOT EXISTS show_date date;
                    ALTER TABLE portal_show ADD COLUMN IF NOT EXISTS start_time time NULL;
                    ALTER TABLE portal_show ADD COLUMN IF NOT EXISTS venue varchar(180) NOT NULL DEFAULT '';
                    ALTER TABLE portal_show ADD COLUMN IF NOT EXISTS address varchar(255) NOT NULL DEFAULT '';
                    ALTER TABLE portal_show ADD COLUMN IF NOT EXISTS host_team varchar(180) NOT NULL DEFAULT '';
                    ALTER TABLE portal_show ADD COLUMN IF NOT EXISTS iea_zone varchar(40) NOT NULL DEFAULT '';
                    ALTER TABLE portal_show ADD COLUMN IF NOT EXISTS iea_region varchar(40) NOT NULL DEFAULT '';
                    ALTER TABLE portal_show ADD COLUMN IF NOT EXISTS status varchar(20) NOT NULL DEFAULT 'planning';
                    ALTER TABLE portal_show ADD COLUMN IF NOT EXISTS entry_deadline date NULL;
                    ALTER TABLE portal_show ADD COLUMN IF NOT EXISTS notes text NOT NULL DEFAULT '';
                    ALTER TABLE portal_show ADD COLUMN IF NOT EXISTS season_id bigint;
                    ALTER TABLE portal_show ADD COLUMN IF NOT EXISTS team_id bigint;
                    ALTER TABLE portal_show ALTER COLUMN name DROP DEFAULT;
                    ALTER TABLE portal_show ALTER COLUMN venue DROP DEFAULT;
                    ALTER TABLE portal_show ALTER COLUMN address DROP DEFAULT;
                    ALTER TABLE portal_show ALTER COLUMN host_team DROP DEFAULT;
                    ALTER TABLE portal_show ALTER COLUMN iea_zone DROP DEFAULT;
                    ALTER TABLE portal_show ALTER COLUMN iea_region DROP DEFAULT;
                    ALTER TABLE portal_show ALTER COLUMN notes DROP DEFAULT;

                    -- ShowClass --------------------------------------------------
                    CREATE TABLE IF NOT EXISTS portal_showclass (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(160) NOT NULL,
                        division varchar(120) NOT NULL DEFAULT '',
                        discipline varchar(30) NOT NULL DEFAULT 'hunt_seat',
                        class_number varchar(30) NOT NULL DEFAULT '',
                        sort_order integer NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
                        show_id bigint NOT NULL
                    );
                    ALTER TABLE portal_showclass ADD COLUMN IF NOT EXISTS name varchar(160) NOT NULL DEFAULT '';
                    ALTER TABLE portal_showclass ADD COLUMN IF NOT EXISTS division varchar(120) NOT NULL DEFAULT '';
                    ALTER TABLE portal_showclass ADD COLUMN IF NOT EXISTS discipline varchar(30) NOT NULL DEFAULT 'hunt_seat';
                    ALTER TABLE portal_showclass ADD COLUMN IF NOT EXISTS class_number varchar(30) NOT NULL DEFAULT '';
                    ALTER TABLE portal_showclass ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0;
                    ALTER TABLE portal_showclass ADD COLUMN IF NOT EXISTS show_id bigint;
                    ALTER TABLE portal_showclass ALTER COLUMN name DROP DEFAULT;
                    ALTER TABLE portal_showclass ALTER COLUMN division DROP DEFAULT;
                    ALTER TABLE portal_showclass ALTER COLUMN class_number DROP DEFAULT;

                    -- ShowEntry --------------------------------------------------
                    CREATE TABLE IF NOT EXISTS portal_showentry (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        entry_type varchar(20) NOT NULL DEFAULT 'individual',
                        is_point_rider boolean NOT NULL DEFAULT false,
                        status varchar(20) NOT NULL DEFAULT 'planned',
                        notes varchar(255) NOT NULL DEFAULT '',
                        rider_id bigint NOT NULL,
                        show_class_id bigint NOT NULL
                    );
                    ALTER TABLE portal_showentry ADD COLUMN IF NOT EXISTS entry_type varchar(20) NOT NULL DEFAULT 'individual';
                    ALTER TABLE portal_showentry ADD COLUMN IF NOT EXISTS is_point_rider boolean NOT NULL DEFAULT false;
                    ALTER TABLE portal_showentry ADD COLUMN IF NOT EXISTS status varchar(20) NOT NULL DEFAULT 'planned';
                    ALTER TABLE portal_showentry ADD COLUMN IF NOT EXISTS notes varchar(255) NOT NULL DEFAULT '';
                    ALTER TABLE portal_showentry ADD COLUMN IF NOT EXISTS rider_id bigint;
                    ALTER TABLE portal_showentry ADD COLUMN IF NOT EXISTS show_class_id bigint;
                    ALTER TABLE portal_showentry ALTER COLUMN notes DROP DEFAULT;

                    -- ShowResult -------------------------------------------------
                    CREATE TABLE IF NOT EXISTS portal_showresult (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        place smallint NULL CHECK (place >= 0),
                        points numeric(5,1) NULL,
                        horse_name varchar(100) NOT NULL DEFAULT '',
                        notes text NOT NULL DEFAULT '',
                        entry_id bigint NOT NULL
                    );
                    ALTER TABLE portal_showresult ADD COLUMN IF NOT EXISTS place smallint NULL;
                    ALTER TABLE portal_showresult ADD COLUMN IF NOT EXISTS points numeric(5,1) NULL;
                    ALTER TABLE portal_showresult ADD COLUMN IF NOT EXISTS horse_name varchar(100) NOT NULL DEFAULT '';
                    ALTER TABLE portal_showresult ADD COLUMN IF NOT EXISTS notes text NOT NULL DEFAULT '';
                    ALTER TABLE portal_showresult ADD COLUMN IF NOT EXISTS entry_id bigint;
                    ALTER TABLE portal_showresult ALTER COLUMN horse_name DROP DEFAULT;
                    ALTER TABLE portal_showresult ALTER COLUMN notes DROP DEFAULT;

                    -- Constraints, guarded by both table and constraint name.
                    DO $$ BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint
                            WHERE conname='portal_show_season_id_fk'
                              AND conrelid='portal_show'::regclass
                        ) THEN
                            ALTER TABLE portal_show ADD CONSTRAINT portal_show_season_id_fk
                            FOREIGN KEY (season_id) REFERENCES portal_season(id)
                            DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint
                            WHERE conname='portal_show_team_id_fk'
                              AND conrelid='portal_show'::regclass
                        ) THEN
                            ALTER TABLE portal_show ADD CONSTRAINT portal_show_team_id_fk
                            FOREIGN KEY (team_id) REFERENCES portal_team(id)
                            DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint
                            WHERE conname='portal_showclass_show_id_fk'
                              AND conrelid='portal_showclass'::regclass
                        ) THEN
                            ALTER TABLE portal_showclass ADD CONSTRAINT portal_showclass_show_id_fk
                            FOREIGN KEY (show_id) REFERENCES portal_show(id)
                            DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint
                            WHERE conname='portal_showentry_rider_id_fk'
                              AND conrelid='portal_showentry'::regclass
                        ) THEN
                            ALTER TABLE portal_showentry ADD CONSTRAINT portal_showentry_rider_id_fk
                            FOREIGN KEY (rider_id) REFERENCES portal_rider(id)
                            DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint
                            WHERE conname='portal_showentry_show_class_id_fk'
                              AND conrelid='portal_showentry'::regclass
                        ) THEN
                            ALTER TABLE portal_showentry ADD CONSTRAINT portal_showentry_show_class_id_fk
                            FOREIGN KEY (show_class_id) REFERENCES portal_showclass(id)
                            DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint
                            WHERE conname='unique_rider_show_class'
                              AND conrelid='portal_showentry'::regclass
                        ) THEN
                            ALTER TABLE portal_showentry ADD CONSTRAINT unique_rider_show_class
                            UNIQUE (show_class_id, rider_id);
                        END IF;
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint
                            WHERE conname='portal_showresult_entry_id_key'
                              AND conrelid='portal_showresult'::regclass
                        ) THEN
                            ALTER TABLE portal_showresult ADD CONSTRAINT portal_showresult_entry_id_key
                            UNIQUE (entry_id);
                        END IF;
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint
                            WHERE conname='portal_showresult_entry_id_fk'
                              AND conrelid='portal_showresult'::regclass
                        ) THEN
                            ALTER TABLE portal_showresult ADD CONSTRAINT portal_showresult_entry_id_fk
                            FOREIGN KEY (entry_id) REFERENCES portal_showentry(id)
                            DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                    END $$;

                    CREATE INDEX IF NOT EXISTS portal_show_season_id_idx ON portal_show(season_id);
                    CREATE INDEX IF NOT EXISTS portal_show_team_id_idx ON portal_show(team_id);
                    CREATE INDEX IF NOT EXISTS portal_showclass_show_id_idx ON portal_showclass(show_id);
                    CREATE INDEX IF NOT EXISTS portal_showentry_rider_id_idx ON portal_showentry(rider_id);
                    CREATE INDEX IF NOT EXISTS portal_showentry_show_class_id_idx ON portal_showentry(show_class_id);
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="Show",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("name", models.CharField(max_length=180)),
                        ("show_date", models.DateField()),
                        ("start_time", models.TimeField(blank=True, null=True)),
                        ("venue", models.CharField(blank=True, max_length=180)),
                        ("address", models.CharField(blank=True, max_length=255)),
                        ("host_team", models.CharField(blank=True, max_length=180)),
                        ("iea_zone", models.CharField(blank=True, max_length=40)),
                        ("iea_region", models.CharField(blank=True, max_length=40)),
                        ("status", models.CharField(choices=[("planning", "Planning"), ("registration", "Registration open"), ("entered", "Entries submitted"), ("complete", "Complete"), ("cancelled", "Cancelled")], default="planning", max_length=20)),
                        ("entry_deadline", models.DateField(blank=True, null=True)),
                        ("notes", models.TextField(blank=True)),
                        ("season", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shows", to="portal.season")),
                        ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shows", to="portal.team")),
                    ],
                    options={"ordering": ["show_date", "name"]},
                ),
                migrations.CreateModel(
                    name="ShowClass",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("name", models.CharField(max_length=160)),
                        ("division", models.CharField(blank=True, max_length=120)),
                        ("discipline", models.CharField(choices=[("hunt_seat", "Hunt Seat"), ("western", "Western"), ("dressage", "Dressage"), ("other", "Other")], default="hunt_seat", max_length=30)),
                        ("class_number", models.CharField(blank=True, max_length=30)),
                        ("sort_order", models.PositiveIntegerField(default=0)),
                        ("show", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="classes", to="portal.show")),
                    ],
                    options={"ordering": ["sort_order", "class_number", "name"]},
                ),
                migrations.CreateModel(
                    name="ShowEntry",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("entry_type", models.CharField(choices=[("individual", "Individual"), ("team", "Team"), ("both", "Individual + Team")], default="individual", max_length=20)),
                        ("is_point_rider", models.BooleanField(default=False)),
                        ("status", models.CharField(choices=[("planned", "Planned"), ("entered", "Entered"), ("scratched", "Scratched")], default="planned", max_length=20)),
                        ("notes", models.CharField(blank=True, max_length=255)),
                        ("rider", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="show_entries", to="portal.rider")),
                        ("show_class", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="portal.showclass")),
                    ],
                    options={"ordering": ["show_class", "rider__last_name", "rider__first_name"]},
                ),
                migrations.CreateModel(
                    name="ShowResult",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("place", models.PositiveSmallIntegerField(blank=True, null=True)),
                        ("points", models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                        ("horse_name", models.CharField(blank=True, max_length=100)),
                        ("notes", models.TextField(blank=True)),
                        ("entry", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="result", to="portal.showentry")),
                    ],
                ),
                migrations.AddConstraint(
                    model_name="showentry",
                    constraint=models.UniqueConstraint(fields=("show_class", "rider"), name="unique_rider_show_class"),
                ),
            ],
        ),
    ]
