from django.db import migrations, models
import django.db.models.deletion


def forward_data(apps, schema_editor):
    Rider = apps.get_model('portal', 'Rider')
    SeasonMembership = apps.get_model('portal', 'SeasonMembership')
    SeasonClass = apps.get_model('portal', 'SeasonClass')
    ShowClass = apps.get_model('portal', 'ShowClass')
    GuardianContact = apps.get_model('portal', 'GuardianContact')
    RiderGuardian = apps.get_model('portal', 'RiderGuardian')

    # Preserve an existing rider login email as the rider contact email.
    for rider in Rider.objects.select_related('user').all():
        if rider.user_id and rider.user.email and not rider.email:
            rider.email = rider.user.email
            rider.save(update_fields=['email'])

    # Infer team level from current grade where possible.
    for membership in SeasonMembership.objects.select_related('rider').all():
        grade = membership.rider.grade
        if grade and 4 <= grade <= 8:
            membership.team_level = 'futures'
        elif grade and 9 <= grade <= 12:
            membership.team_level = 'upper'
        membership.save(update_fields=['team_level'])

    # Convert existing show-specific class names into a season catalog, and link
    # every existing entry's rider to the corresponding season class.
    for show_class in ShowClass.objects.select_related('show__season').all():
        sc, _ = SeasonClass.objects.get_or_create(
            season=show_class.show.season,
            name=show_class.name,
            team_level='both',
            defaults={
                'division': show_class.division,
                'discipline': show_class.discipline,
                'sort_order': show_class.sort_order,
                'active': True,
            },
        )
        show_class.season_class = sc
        show_class.save(update_fields=['season_class'])
        for entry in show_class.entries.select_related('rider').all():
            membership, _ = SeasonMembership.objects.get_or_create(
                rider=entry.rider,
                season=show_class.show.season,
                defaults={'team_level': 'futures' if entry.rider.grade and entry.rider.grade <= 8 else 'upper' if entry.rider.grade and entry.rider.grade >= 9 else ''},
            )
            membership.classes.add(sc)

    # Preserve existing parent login relationships as richer contact records.
    for rider in Rider.objects.all():
        for user in rider.guardians.all():
            contact, _ = GuardianContact.objects.get_or_create(
                user=user,
                defaults={
                    'team_id': rider.team_id,
                    'first_name': user.first_name or user.username,
                    'last_name': user.last_name or '',
                    'email': user.email or '',
                },
            )
            RiderGuardian.objects.get_or_create(rider=rider, guardian=contact, defaults={'relationship': 'Parent/Guardian'})


class Migration(migrations.Migration):
    dependencies = [('portal', '0002_competition_management')]

    # v1.2.0/1.2.1 reached users with schema objects that could already exist
    # while Django still considered migration 0003 unapplied. Reconcile the
    # physical PostgreSQL schema idempotently, then record the normal Django
    # model state. This allows both clean upgrades and partially-prepared DBs.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=r"""
                    -- Rider email -------------------------------------------------
                    ALTER TABLE portal_rider
                        ADD COLUMN IF NOT EXISTS email varchar(254) NOT NULL DEFAULT '';
                    ALTER TABLE portal_rider ALTER COLUMN email DROP DEFAULT;

                    -- GuardianContact ---------------------------------------------
                    CREATE TABLE IF NOT EXISTS portal_guardiancontact (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        first_name varchar(80) NOT NULL,
                        last_name varchar(80) NOT NULL,
                        email varchar(254) NOT NULL DEFAULT '',
                        phone varchar(30) NOT NULL DEFAULT '',
                        notes text NOT NULL DEFAULT '',
                        team_id bigint NOT NULL,
                        user_id integer NULL
                    );
                    ALTER TABLE portal_guardiancontact ADD COLUMN IF NOT EXISTS first_name varchar(80) NOT NULL DEFAULT '';
                    ALTER TABLE portal_guardiancontact ADD COLUMN IF NOT EXISTS last_name varchar(80) NOT NULL DEFAULT '';
                    ALTER TABLE portal_guardiancontact ADD COLUMN IF NOT EXISTS email varchar(254) NOT NULL DEFAULT '';
                    ALTER TABLE portal_guardiancontact ADD COLUMN IF NOT EXISTS phone varchar(30) NOT NULL DEFAULT '';
                    ALTER TABLE portal_guardiancontact ADD COLUMN IF NOT EXISTS notes text NOT NULL DEFAULT '';
                    ALTER TABLE portal_guardiancontact ADD COLUMN IF NOT EXISTS team_id bigint;
                    ALTER TABLE portal_guardiancontact ADD COLUMN IF NOT EXISTS user_id integer;
                    ALTER TABLE portal_guardiancontact ALTER COLUMN first_name DROP DEFAULT;
                    ALTER TABLE portal_guardiancontact ALTER COLUMN last_name DROP DEFAULT;
                    ALTER TABLE portal_guardiancontact ALTER COLUMN email DROP DEFAULT;
                    ALTER TABLE portal_guardiancontact ALTER COLUMN phone DROP DEFAULT;
                    ALTER TABLE portal_guardiancontact ALTER COLUMN notes DROP DEFAULT;

                    -- SeasonClass -------------------------------------------------
                    CREATE TABLE IF NOT EXISTS portal_seasonclass (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(160) NOT NULL,
                        team_level varchar(20) NOT NULL DEFAULT 'both',
                        division varchar(120) NOT NULL DEFAULT '',
                        discipline varchar(30) NOT NULL DEFAULT 'hunt_seat',
                        sort_order integer NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
                        active boolean NOT NULL DEFAULT true,
                        season_id bigint NOT NULL
                    );
                    ALTER TABLE portal_seasonclass ADD COLUMN IF NOT EXISTS name varchar(160) NOT NULL DEFAULT '';
                    ALTER TABLE portal_seasonclass ADD COLUMN IF NOT EXISTS team_level varchar(20) NOT NULL DEFAULT 'both';
                    ALTER TABLE portal_seasonclass ADD COLUMN IF NOT EXISTS division varchar(120) NOT NULL DEFAULT '';
                    ALTER TABLE portal_seasonclass ADD COLUMN IF NOT EXISTS discipline varchar(30) NOT NULL DEFAULT 'hunt_seat';
                    ALTER TABLE portal_seasonclass ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0;
                    ALTER TABLE portal_seasonclass ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT true;
                    ALTER TABLE portal_seasonclass ADD COLUMN IF NOT EXISTS season_id bigint;
                    ALTER TABLE portal_seasonclass ALTER COLUMN name DROP DEFAULT;
                    ALTER TABLE portal_seasonclass ALTER COLUMN division DROP DEFAULT;

                    -- SeasonMembership additions ---------------------------------
                    ALTER TABLE portal_seasonmembership
                        ADD COLUMN IF NOT EXISTS team_level varchar(20) NOT NULL DEFAULT '';
                    ALTER TABLE portal_seasonmembership ALTER COLUMN team_level DROP DEFAULT;

                    CREATE TABLE IF NOT EXISTS portal_seasonmembership_classes (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        seasonmembership_id bigint NOT NULL,
                        seasonclass_id bigint NOT NULL
                    );

                    -- ShowClass season catalog link -------------------------------
                    ALTER TABLE portal_showclass
                        ADD COLUMN IF NOT EXISTS season_class_id bigint NULL;

                    -- RiderGuardian -----------------------------------------------
                    CREATE TABLE IF NOT EXISTS portal_riderguardian (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        relationship varchar(50) NOT NULL DEFAULT '',
                        primary_contact boolean NOT NULL DEFAULT false,
                        guardian_id bigint NOT NULL,
                        rider_id bigint NOT NULL
                    );
                    ALTER TABLE portal_riderguardian ADD COLUMN IF NOT EXISTS relationship varchar(50) NOT NULL DEFAULT '';
                    ALTER TABLE portal_riderguardian ADD COLUMN IF NOT EXISTS primary_contact boolean NOT NULL DEFAULT false;
                    ALTER TABLE portal_riderguardian ADD COLUMN IF NOT EXISTS guardian_id bigint;
                    ALTER TABLE portal_riderguardian ADD COLUMN IF NOT EXISTS rider_id bigint;
                    ALTER TABLE portal_riderguardian ALTER COLUMN relationship DROP DEFAULT;

                    -- Constraints. PostgreSQL does not provide ADD CONSTRAINT IF
                    -- NOT EXISTS, so inspect pg_constraint in guarded DO blocks.
                    DO $$ BEGIN
                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='portal_guardiancontact_team_id_fk' AND conrelid='portal_guardiancontact'::regclass) THEN
                            ALTER TABLE portal_guardiancontact ADD CONSTRAINT portal_guardiancontact_team_id_fk
                            FOREIGN KEY (team_id) REFERENCES portal_team(id) DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='portal_guardiancontact_user_id_fk' AND conrelid='portal_guardiancontact'::regclass) THEN
                            ALTER TABLE portal_guardiancontact ADD CONSTRAINT portal_guardiancontact_user_id_fk
                            FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='portal_guardiancontact_user_id_uniq' AND conrelid='portal_guardiancontact'::regclass) THEN
                            ALTER TABLE portal_guardiancontact ADD CONSTRAINT portal_guardiancontact_user_id_uniq UNIQUE (user_id);
                        END IF;

                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='portal_seasonclass_season_id_fk' AND conrelid='portal_seasonclass'::regclass) THEN
                            ALTER TABLE portal_seasonclass ADD CONSTRAINT portal_seasonclass_season_id_fk
                            FOREIGN KEY (season_id) REFERENCES portal_season(id) DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='unique_season_class_by_team' AND conrelid='portal_seasonclass'::regclass) THEN
                            ALTER TABLE portal_seasonclass ADD CONSTRAINT unique_season_class_by_team
                            UNIQUE (season_id, name, team_level);
                        END IF;

                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='portal_seasonmembership_classes_membership_fk' AND conrelid='portal_seasonmembership_classes'::regclass) THEN
                            ALTER TABLE portal_seasonmembership_classes ADD CONSTRAINT portal_seasonmembership_classes_membership_fk
                            FOREIGN KEY (seasonmembership_id) REFERENCES portal_seasonmembership(id) DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='portal_seasonmembership_classes_class_fk' AND conrelid='portal_seasonmembership_classes'::regclass) THEN
                            ALTER TABLE portal_seasonmembership_classes ADD CONSTRAINT portal_seasonmembership_classes_class_fk
                            FOREIGN KEY (seasonclass_id) REFERENCES portal_seasonclass(id) DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='portal_seasonmembership_classes_uniq' AND conrelid='portal_seasonmembership_classes'::regclass) THEN
                            ALTER TABLE portal_seasonmembership_classes ADD CONSTRAINT portal_seasonmembership_classes_uniq
                            UNIQUE (seasonmembership_id, seasonclass_id);
                        END IF;

                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='portal_showclass_season_class_id_fk' AND conrelid='portal_showclass'::regclass) THEN
                            ALTER TABLE portal_showclass ADD CONSTRAINT portal_showclass_season_class_id_fk
                            FOREIGN KEY (season_class_id) REFERENCES portal_seasonclass(id) DEFERRABLE INITIALLY DEFERRED;
                        END IF;

                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='portal_riderguardian_guardian_id_fk' AND conrelid='portal_riderguardian'::regclass) THEN
                            ALTER TABLE portal_riderguardian ADD CONSTRAINT portal_riderguardian_guardian_id_fk
                            FOREIGN KEY (guardian_id) REFERENCES portal_guardiancontact(id) DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='portal_riderguardian_rider_id_fk' AND conrelid='portal_riderguardian'::regclass) THEN
                            ALTER TABLE portal_riderguardian ADD CONSTRAINT portal_riderguardian_rider_id_fk
                            FOREIGN KEY (rider_id) REFERENCES portal_rider(id) DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='unique_rider_guardian_contact' AND conrelid='portal_riderguardian'::regclass) THEN
                            ALTER TABLE portal_riderguardian ADD CONSTRAINT unique_rider_guardian_contact
                            UNIQUE (rider_id, guardian_id);
                        END IF;
                    END $$;

                    -- Foreign-key indexes Django would normally create.
                    CREATE INDEX IF NOT EXISTS portal_guardiancontact_team_id_idx ON portal_guardiancontact(team_id);
                    CREATE INDEX IF NOT EXISTS portal_seasonclass_season_id_idx ON portal_seasonclass(season_id);
                    CREATE INDEX IF NOT EXISTS portal_seasonmembership_classes_membership_idx ON portal_seasonmembership_classes(seasonmembership_id);
                    CREATE INDEX IF NOT EXISTS portal_seasonmembership_classes_class_idx ON portal_seasonmembership_classes(seasonclass_id);
                    CREATE INDEX IF NOT EXISTS portal_showclass_season_class_id_idx ON portal_showclass(season_class_id);
                    CREATE INDEX IF NOT EXISTS portal_riderguardian_guardian_id_idx ON portal_riderguardian(guardian_id);
                    CREATE INDEX IF NOT EXISTS portal_riderguardian_rider_id_idx ON portal_riderguardian(rider_id);
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='rider',
                    name='email',
                    field=models.EmailField(blank=True, max_length=254),
                ),
                migrations.CreateModel(
                    name='GuardianContact',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('first_name', models.CharField(max_length=80)),
                        ('last_name', models.CharField(max_length=80)),
                        ('email', models.EmailField(blank=True, max_length=254)),
                        ('phone', models.CharField(blank=True, max_length=30)),
                        ('notes', models.TextField(blank=True)),
                        ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_contacts', to='portal.team')),
                        ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_contact', to='auth.user')),
                    ],
                    options={'ordering': ['last_name', 'first_name']},
                ),
                migrations.CreateModel(
                    name='SeasonClass',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=160)),
                        ('team_level', models.CharField(choices=[('futures', 'Futures Team'), ('upper', 'Upper School Team'), ('both', 'Both teams')], default='both', max_length=20)),
                        ('division', models.CharField(blank=True, max_length=120)),
                        ('discipline', models.CharField(choices=[('hunt_seat', 'Hunt Seat'), ('western', 'Western'), ('dressage', 'Dressage'), ('other', 'Other')], default='hunt_seat', max_length=30)),
                        ('sort_order', models.PositiveIntegerField(default=0)),
                        ('active', models.BooleanField(default=True)),
                        ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_classes', to='portal.season')),
                    ],
                    options={'ordering': ['team_level', 'sort_order', 'name']},
                ),
                migrations.AddConstraint(
                    model_name='seasonclass',
                    constraint=models.UniqueConstraint(fields=('season', 'name', 'team_level'), name='unique_season_class_by_team'),
                ),
                migrations.AddField(
                    model_name='seasonmembership',
                    name='team_level',
                    field=models.CharField(blank=True, choices=[('futures', 'Futures Team'), ('upper', 'Upper School Team')], max_length=20),
                ),
                migrations.AddField(
                    model_name='seasonmembership',
                    name='classes',
                    field=models.ManyToManyField(blank=True, related_name='rider_memberships', to='portal.seasonclass'),
                ),
                migrations.AddField(
                    model_name='showclass',
                    name='season_class',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='show_classes', to='portal.seasonclass'),
                ),
                migrations.CreateModel(
                    name='RiderGuardian',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('relationship', models.CharField(blank=True, help_text='Example: Parent, Mother, Father, Guardian', max_length=50)),
                        ('primary_contact', models.BooleanField(default=False)),
                        ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_links', to='portal.guardiancontact')),
                        ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='portal.rider')),
                    ],
                ),
                migrations.AddConstraint(
                    model_name='riderguardian',
                    constraint=models.UniqueConstraint(fields=('rider', 'guardian'), name='unique_rider_guardian_contact'),
                ),
            ],
        ),
        migrations.RunPython(forward_data, migrations.RunPython.noop),
    ]
