# Generated by Django 5.2.17 on 2026-09-11 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0042_v214_show_horse_list_documents"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="showbudgetline",
            options={
                "ordering": [
                    "scope",
                    "kind",
                    "category__sort_order",
                    "category__name",
                    "description",
                    "id",
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="showentry",
            options={
                "ordering": [
                    "show_class",
                    "rider__last_name",
                    "rider__first_name",
                    "competition_track",
                ]
            },
        ),
        migrations.AlterField(
            model_name="reimbursementrequest",
            name="expense_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="showdayupdate",
            name="send_email",
            field=models.BooleanField(
                default=True,
                help_text="Also email recipients who allow announcement email.",
            ),
        ),
    ]
