from django.db import migrations, models
import django.db.models.deletion

def normalize_statement_recipient_roles(apps,schema_editor):
    Link=apps.get_model("portal","ReceivableAccountPerson")
    for link in Link.objects.filter(role="statement_recipient").iterator():
        link.statement_recipient=True
        link.role="billing_contact"
        link.save(update_fields=["statement_recipient","role"])

class Migration(migrations.Migration):
    dependencies=[("portal","0096_v350_generic_financial_transactions")]
    operations=[
        migrations.RunPython(normalize_statement_recipient_roles,migrations.RunPython.noop),
        migrations.AlterField(model_name="receivableaccountperson",name="role",field=models.CharField(choices=[("responsible_party","Responsible party"),("billing_contact","Billing contact"),("participant","Rider / participant")],default="participant",max_length=24)),
        migrations.CreateModel(name="BankImportProfile",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=120)),("file_type",models.CharField(choices=[("csv","CSV"),("xlsx","Excel")],default="csv",max_length=8)),("column_mapping",models.JSONField(default=dict)),("active",models.BooleanField(default=True)),("created_at",models.DateTimeField(auto_now_add=True)),("financial_account",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="import_profiles",to="portal.financialaccount")),("team",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="bank_import_profiles",to="portal.team"))],options={"ordering":["name","id"]}),
        migrations.CreateModel(name="BankImportBatch",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("finance_domain",models.CharField(choices=[("general","General barn"),("iea","IEA")],max_length=12)),("source_name",models.CharField(max_length=255)),("source_fingerprint",models.CharField(max_length=64)),("status",models.CharField(choices=[("staged","Staged"),("reviewed","Reviewed"),("completed","Completed"),("void","Void")],default="staged",max_length=12)),("imported_at",models.DateTimeField(auto_now_add=True)),("financial_account",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="import_batches",to="portal.financialaccount")),("profile",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="batches",to="portal.bankimportprofile")),("team",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="bank_import_batches",to="portal.team"))],options={"ordering":["-imported_at","-id"]}),
        migrations.CreateModel(name="ImportedBankTransaction",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("transaction_date",models.DateField()),("posted_date",models.DateField(blank=True,null=True)),("amount",models.DecimalField(decimal_places=2,max_digits=12)),("direction",models.CharField(choices=[("credit","Money in"),("debit","Money out")],max_length=8)),("description",models.CharField(max_length=255)),("reference",models.CharField(blank=True,max_length=160)),("external_id",models.CharField(blank=True,max_length=160)),("row_fingerprint",models.CharField(max_length=64)),("raw_data",models.JSONField(default=dict)),("status",models.CharField(choices=[("staged","Staged"),("matched","Matched"),("reconciled","Reconciled"),("ignored","Ignored")],default="staged",max_length=12)),("created_at",models.DateTimeField(auto_now_add=True)),("batch",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="transactions",to="portal.bankimportbatch"))],options={"ordering":["transaction_date","id"]}),
        migrations.CreateModel(name="ReconciliationMatch",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("status",models.CharField(choices=[("suggested","Suggested"),("confirmed","Confirmed"),("rejected","Rejected")],default="suggested",max_length=12)),("score",models.PositiveSmallIntegerField(default=0)),("rationale",models.CharField(blank=True,max_length=255)),("confirmed_at",models.DateTimeField(blank=True,null=True)),("created_at",models.DateTimeField(auto_now_add=True)),("financial_transaction",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="bank_matches",to="portal.financialtransaction")),("imported_transaction",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="matches",to="portal.importedbanktransaction"))],options={"ordering":["-score","id"]}),
        migrations.AddConstraint(model_name="bankimportprofile",constraint=models.UniqueConstraint(fields=("team","financial_account","name"),name="unique_bank_import_profile_account_name")),
        migrations.AddConstraint(model_name="bankimportbatch",constraint=models.UniqueConstraint(fields=("team","financial_account","source_fingerprint"),name="unique_bank_import_batch_fingerprint")),
        migrations.AddConstraint(model_name="importedbanktransaction",constraint=models.CheckConstraint(condition=models.Q(amount__gt=0),name="imported_bank_transaction_amount_gt_zero")),
        migrations.AddConstraint(model_name="importedbanktransaction",constraint=models.UniqueConstraint(fields=("batch","row_fingerprint"),name="unique_imported_bank_transaction_batch_row")),
        migrations.AddConstraint(model_name="reconciliationmatch",constraint=models.UniqueConstraint(fields=("imported_transaction","financial_transaction"),name="unique_reconciliation_candidate")),
    ]
