# Generated by Django 5.2.17 on 2026-09-21 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0110_repair_legacy_iea_receivable_account_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='portal.team')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FacilitySpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('space_type', models.CharField(choices=[('barn', 'Barn / Building'), ('arena', 'Arena / Ring'), ('stall', 'Stall'), ('pasture', 'Pasture / Paddock'), ('feed_room', 'Feed Room'), ('tack_room', 'Tack Room'), ('storage', 'Storage'), ('wash_area', 'Wash / Grooming Area'), ('other', 'Other')], default='other', max_length=24)),
                ('reservable', models.BooleanField(default=False)),
                ('housing_capable', models.BooleanField(default=False)),
                ('turnout_capable', models.BooleanField(default=False)),
                ('inventory_storage_capable', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='portal.facility')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='portal.facilityspace')),
            ],
            options={
                'ordering': ['facility__name', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HorsePastureAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turnout_type', models.CharField(choices=[('primary', 'Primary'), ('temporary', 'Temporary'), ('other', 'Other')], default='primary', max_length=16)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasture_assignments', to='portal.horse')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pasture_assignments', to='portal.facilityspace')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HorseStallAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stall_assignments', to='portal.horse')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stall_assignments', to='portal.facilityspace')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('source_type', models.CharField(blank=True, max_length=80)),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='portal.facilityspace')),
            ],
            options={
                'ordering': ['starts_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(fields=('team', 'name'), name='unique_facility_name_per_team'),
        ),
        migrations.AddConstraint(
            model_name='facilityspace',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('facility', 'parent', 'name'), name='unique_facility_space_parent_name'),
        ),
        migrations.AddConstraint(
            model_name='facilityspace',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('facility', 'name'), name='unique_facility_root_space_name'),
        ),
    ]
